image:
  registry: "quay.io"
  name: "giantswarm/template-operator"
  tag: "[[ .Version ]]"
pod:
  user:
    id: 1000
  group:
    id: 1000
project:
  name: "template-operator"
  version: "[[ .Version ]]"
