registry:
  domain: docker.io
image:
  name: "giantswarm/template-operator"
  tag: "[[ .Version ]]"
pod:
  user:
    id: 1000
  group:
    id: 1000
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
