{{- define "secret.yaml" -}}
service:
  todo:
    structure:
      token: "xyz"
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  secret.yaml: {{ include "secret.yaml" . | b64enc | quote }}

