apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    app: {{ .Values.project.name }}
    version: {{ .Values.project.version }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8000
  selector:
    app: {{ .Values.project.name }}
    version: {{ .Values.project.version }}
